contacts/urls.py
from django.urls import path

from .views import (
    index,
)

urlpatterns = [
    path("", index, name="index"),
]

app_name = "contacts"

metal_store/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('', include('contacts.urls', namespace='contacts'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, )

store/urls.py
from django.urls import path

from .views import (
    ProductListView,
    ProductDetailView,
)

urlpatterns = [
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
]

app_name = "store"

contacts/models.py
from django.db import models


class PhoneNumber(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.IntegerField()

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Phone Numbers"

    def __str__(self):
        return f"{self.name} {self.phone_number}"


class WorkSchedule(models.Model):
    days = models.CharField(max_length=255)
    hours = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.days} {self.hours}"


class ContactEmail(models.Model):
    email = models.EmailField()

    def __str__(self):
        return f"{self.email}"


class CallBack(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date", )

    def __str__(self):
        return f"{self.name} {str(self.phone_number)} {str(self.email)}"

store/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.name}"


class Sizes(models.Model):
    size = models.PositiveIntegerField()

    class Meta:
        ordering = ("size",)
        verbose_name_plural = "sizes"

    def __str__(self):
        return f"{self.size}"


class CategorySizes(models.Model):
    name = models.CharField(max_length=255)
    size = models.ManyToManyField(Sizes, related_name="category_sizes", blank=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "categories sizes"

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    price = models.CharField(max_length=255)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="categories"
    )
    steel_mark = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True)
    sizes = models.ManyToManyField(CategorySizes, related_name="sizes", blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

contacts/forms.py
from django import forms

from .models import CallBack


class ContactForm(forms.ModelForm):
    class Meta:
        model = CallBack
        fields = ["name", "phone_number", "email", "message"]
        

store/forms.py
from django import forms

from store.models import Category


class ProductSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Пошук"
            }
        )
    )


class CategorySearchForm(forms.Form):
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        required=False,
        label="",
        widget=forms.CheckboxSelectMultiple
    )

contacts/views.py
from django.shortcuts import render, redirect

from .models import PhoneNumber
from .forms import ContactForm


def index(request):
    phone_numbers = PhoneNumber.objects.all()
    
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("contacts:index")
    else:
        form = ContactForm()

    context = {
        "phone_numbers": phone_numbers,
        "form": form
    }
    
    return render(request, "contacts/index.html", context)
    

store/views.py
from django.shortcuts import render
from django.views import generic

from .forms import ProductSearchForm, CategorySearchForm
from .models import (
    Product,
)


class ProductListView(generic.ListView):
    model = Product
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        categories = self.request.GET.getlist("category")

        context["search_form"] = ProductSearchForm(initial={"name": name})
        context["category_form"] = CategorySearchForm(initial={"category": categories})

        return context

    def get_queryset(self):
        queryset = Product.objects.all().select_related("category")

        name_form = ProductSearchForm(self.request.GET)
        if name_form.is_valid():
            name = name_form.cleaned_data.get("name")
            if name:
                queryset = queryset.filter(name__icontains=name)

        category_form = CategorySearchForm(self.request.GET)
        if category_form.is_valid():
            categories = category_form.cleaned_data.get("category")
            if categories:
                queryset = queryset.filter(category__in=categories)

        return queryset


class ProductDetailView(generic.DetailView):
    model = Product

templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{% block title %}Магазин виробів з металів{% endblock %}</title>

    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/metalStore.css' %}">
</head>

<body>
{% block topHeader %}
{% include "includes/topHeader.html" %}
{% endblock %}

{% block header %}
{% include "includes/header.html" %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="{% static 'js/store.js' %}"></script>
<!--<script type="module" src="{% static 'js/dropdown.js' %}"></script>-->
</body>
</html>

templates/contacts/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<main xmlns="http://www.w3.org/1999/html">
    <section id="categories" class='row justify-content-center align-items-center'>
        <div class="row justify-content-center pb-3 m-0 section-header">
            <h2 class='col-lg-6 col-12'>Категорії</h2>
            <p class='col-lg-8 col-12'> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Suspendisse faucibus porta ullamcorper.Aliquam quis placerat massa, vel dictum magna.
                Suspendisse vestibulum leo vitae purus facilisis vehicula.
                Integer tincidunt ac ante sit amet feugiat. Vivamus blandit tristique ante vitae vehicula.</p>
        </div>
        <article>
        </article>
            <a type="button" class="btn btn-outline-primary col-lg-2 col-10"  href="{% url 'store:product-list' %}">
                Переглянути всі товари
            </a>
    </section>
    <section id="contacts" class='bg-white'>
        <div class="row justify-content-center pb-3 m-0 section-header">
            <h2 class='col-lg-6 col-12'>Зворотній зв'язок</h2>
            <p class='col-lg-8 col-12'> Потрібна допомога або актуальний прайс-лист? Залиште свої
                контактні дані, і ми зв'яжемося з Вами протягом дня, або зателефонуйте в наш контакт-центр.
                Наши менеджери передзвонять Вам протягом дня та з радістю нададуть Вам всю необхідну
                інформацію, чи допоможуть вирішити будь-які питання.</p>
        </div>
        <article class="container">
        <div class='row justify-content-between align-items-start text-center'>
            <address class="col-lg-4 col-12 text-lg-end text-center">
                <h3 class="mb-4">Наші контакти</h3>
                <table class='d-inline-block text-start text-primary'>
                    {% if phone_numbers %}
                    {% for number in phone_numbers %}
                    <tr>
                        <td class="d-inline-flex fw-bold bi bi-phone"></td>
                        <td class="pb-3"><h5 class="fw-bold">{{ number.name }}</h5></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="pb-4"><a href="tel:380 95 66 54 123">{{ number.phone_number }}</a></td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </table>
            </address>
            <form action="/" method="post" id="contact-form" class="contact-form col-lg-6 col-12">
                <h3>Заповніть форму і ми вам передзвонимо протягом дня.</h3>
                {% csrf_token %}
                <fieldset id="input-fields">
                    <p>
                        {{ form.name }}
                    </p>
                    <p>
                        {{ form.phone_number }}
                    </p>
                    <p>
                        {{ form.email }}
                    </p>
                    <p>
                        {{ form.message }}
                    </p>
                </fieldset>
                <button type="submit">Надіслати</button>
            </form>
        </div>
        </article>
    </section>
    <section id="about" class='bg-tertiary'>
        <div class="row justify-content-center pb-3 m-0 section-header">
            <h2 class='col-lg-6 col-12'>Про нас</h2>
            <p class='col-lg-8 col-12'> Наші співробітники володіють усіма необхідними якостями,
                щоб клієнт залишився задоволеним своєю покупкою.
                Чому саме вам варто співпрацювати з нами? Розглядаючи переваги нашої організації,
                варто звернути увагу на наступне:</p>
        </div>
        <article class="container">
            <div class="row row-cols-1 row-cols-lg-3 g-4 g-lg-3">
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/24-hours-timer-11314.svg' %}"
                                        alt="Пунктуальність"/>
                            </div>
                            <h5 class="card-title">Пунктуальність</h5>
                            <p class="card-text">Ми гарантуємо пунктуальність та своєчасність виконання замовлення.</p>
                        </div>
                    </div>
                </div>
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/badge-1312.svg' %}"
                                        alt="Висока кваліфікація та професіоналізм"/>
                            </div>
                            <h5 class="card-title">Висока кваліфікація та професіоналізм</h5>
                            <p class="card-text">Висока кваліфікація та професіоналізм наших фахівців
                                дозволяє виключити будь які помилки з нашого боку.</p>
                        </div>
                    </div>
                </div>
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/empty-papers-or-sheet-black-outline-19844.svg' %}"
                                        alt="Широкий асортимент"/>
                            </div>
                            <h5 class="card-title">Широкий асортимент</h5>
                            <p class="card-text">Запорукою успіху є широкий асортимент сертифікованої продукції.</p>
                        </div>
                    </div>
                </div>
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/calendar-11003.svg' %}"
                                        alt="Широкий асортимент"/>
                            </div>
                            <h5 class="card-title">Багаторічний досвід</h5>
                            <p class="card-text">Ми багато років працюємо на ринку металопрокату.</p>
                        </div>
                    </div>
                </div>
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/sale-sticker-11295.svg' %}"
                                        alt="Система знижок"/>
                            </div>
                            <h5 class="card-title">Система знижок</h5>
                            <p class="card-text">Ми маємо систему знижок для постійних клієнтів.</p>
                        </div>
                    </div>
                </div>
                <div class="col align-items-start">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                            <div class="rounded-image">
                                <img
                                        class="card-img-start"
                                        src="{% static '/images/list-6240.svg' %}"
                                        alt="Різноманітні послуги."/>
                            </div>
                            <h5 class="card-title">Різноманітні послуги.</h5>
                            <p class="card-text">Виконуємо послуги з металообробки та виготовлення металовиробів на
                                замовлення.</p>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>
</main>

{% endblock %}

templates/includes/footer.html
{% load static %}

<footer id="footer" class="container-fluid bg-primary text-white bg-opacity-75">
    <div class="container">
        <div class="row py-4">
            <div class="col-lg-4 col-12 text-lg-start text-center">
                <h3 class="pb-5">Як нас знайти?</h3>
                <address>
                    <h5>Графік роботи</h5>
                    <p class="pb-3"> {{ work_schedule.days }} {{ work_schedule.hours }}</p>
                    <h5>Адреса</h5>
                    <p class="pb-3">Україна, м. Харків, вул. Юр'ївська 17</p>
                    <h5>E-mail</h5>
                    <p class="pb-3">{{ contact_email.email }}</p>
                    <h5>Телефон</h5>
                    <p class="pb-3"> +{{ phone_number.phone_number }}</p>
                </address>
            </div>
            <div class="col-lg-8 col-12">
                <div class="ratio ratio-21x9">
                    <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2564.9659213485334!2d36.252760776641814!3d49.9932483715085!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4127a094ebdca347%3A0x1b61a2b1509c8646!2sYur&#39;ivs&#39;ka%20St%2C%2017%2C%20Kharkiv%2C%20Kharkivs&#39;ka%20oblast%2C%20Ukraine%2C%2061000!5e0!3m2!1sen!2spl!4v1724768478084!5m2!1sen!2spl"
                            style="border:0;"
                            allowfullscreen=""
                            loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade">
                    </iframe>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<header class="shadow-sm mb-0 bg-white">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static '/images/vector-stal.svg' %}" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown" id="first-dropdown">
                        <p class="d-inline-flex">
                            <a class="nav-link" href="{% url 'store:product-list' %}">
                                Товари
                            </a>
                            <button class="btn-span btn-dropdown">
                                <span class="dropdown-toggle btn-dropdown-span"></span>
                            </button>
                        </p>
                        {% if categories %}
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            <li class="nav-item dropend submenu">
                                <p class="d-inline-flex">
                                    <a class="dropdown-item" href="{% url 'store:product-list' %}">{{ category.name }}</a>
                                    <button class="btn-span btn-dropend">
                                        <span class="dropdown-toggle btn-dropend-span"></span>
                                    </button>
                                </p>
                                <ul class="dropdown-menu">
                                    {% if category.products %}
                                    {% for product in category.products %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'store:product-detail' product.pk %}">{{ product.name }}</a>
                                    </li>
                                    {% endfor %}
                                    {% else %}
                                    <li>
                                        <a class="dropdown-item" href="#">No products available</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/#about">Про нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#footer">Як нас знайти?</a>
                    </li>
                </ul>
                <form class="d-inline-flex" id="search-form" role="search" method="get" action="{% url 'store:product-list' %}">
                {{ search_form.as_p }}
                <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
                </form>
            </div>
        </div>
    </nav>
</header>

templates/includes/topHeader.html
{% load static %}


<div class="top-header container-fluid d-flex align-items-center justify-content-center position-fixed">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-6 d-flex justify-content-start">
                <div class="row contact-links">
                    <i class="col-lg-6 bi bi-phone text-white d-flex align-items-center">
                        <a class="position-relative text-white" href="tel:+{{ phone_number.phone_number }}"> +{{ phone_number.phone_number }}</a></i>
                    <i class="col-lg-6 bi bi-envelope text-white d-flex align-items-center">
                        <a class="position-relative text-white" href="mailto:{{ contact_email.email }}">
                            {{ contact_email.email }}</a></i>
                </div>
            </div>
            <div class="col-lg-4 col-6 d-flex justify-content-end">
                <button class="bg-transparent"><a href="/#contact-form">Замовити зворотній зв&apos;зок</a></button>
            </div>
        </div>
    </div>
</div>

templates/store/product_detail.html
{% extends "base.html" %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<section class="product-detail container my-3">
    <div class="row">
        <figure class="product-main-img col-lg-5">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
        </figure>
        <article class="col-lg-7">
            <div class="product-main-description ">
                <h1 class="product-title text-bold my-3">{{ product.name }}</h1>
                <h6 class="product-category text-bold my-3">Категорія: {{ product.category }}</h6>
                <p class="product-price mb-5">{{ product.price }}</p>
            </div>
            <div class="product-details my-3">
                <p class="product-details-title fw-bolder mb-1">Про товар</p>
                <p class="product-details-description mb-5">
                    {{ product.description }}
                </p>
                <p class="fw-bolder mb-1">Розмір:</p>
                <p class="product-details-size-size">{{ product.size }}</p>
            </div>
        </article>
    </div>
</section>
{% endblock %}

templates/store/product_list.html
{% extends "base.html" %}

{% block title %}Категорії товарів{% endblock %}

{% block content %}
  <section class="mt-3 products-list container-fluid bg-white">
    <div class="row">
      <div class="col-lg-1 col-0"></div>
      <aside class="check-box col-lg-1 col-3 m-0">
        <form method="get" class="" action="{% url 'store:product-list' %}">
          <h3 class="mb-3">Категорії</h3>
          <hr>
          {{ category_form.as_p }}
          <button class="btn btn-outline-primary mt-3" type="submit">Показати</button>
        </form>
      </aside>
      <article class="col-lg-10 col-9 p-sm-1 position-relative">
        <ul class="row row-cols-1 row-cols-lg-4 g-4 g-lg-3 p-sm-1 position-absolute overflow-y-auto product-box">
          {% if product_list %}
          {% for product in product_list %}
          <li class="col">
            <div class="card product-card text-center">
              <img src="{{ product.image.url }}" alt="{{ product.name }}">
              <div class="card-body">
                <h5 class="card-title pb-3">{{ product.name }}</h5>
                <p class="card-text pb-2 text-start"></p>
                <p class="card-text pb-4 text-start"><span>{{ product.price }}</span></p>
                  <a type="button" class="btn btn-outline-primary" href="{% url 'store:product-detail' product.id %}">Show More</a>
              </div>
            </div>
          </li>
          {% endfor %}
          {% endif %}
        </ul>
      </article>
    </div>
  </section>
{% endblock %}